# SAM Template: Parking Step Function (IoT Parking Simulation)
# Purpose:
# - Orchestrate a demo flow per device:
#   1) Enqueue device event to SQS (decouple / async processing)
#   2) Poll shadow sync status with a bounded retry loop
#   3) Updates DB
#   4) Notify (SNS) only if shadow did not sync after max attempts
#
# Notes:
# - Integrates with existing Lambda functions (UpdateDeviceShadow, GetShadow, UpdateDB, SNSNotify).
# - Each device is processed independently inside a Map state.

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demo Step Function for IoT Parking Simulation (Free Tier Friendly)

Parameters:
  EnvironmentKey:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment where this stack is deployed (dev/staging/prod)

Resources:

  ParkingStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub parking-simulation-${EnvironmentKey}
      RoleArn:
        Fn::ImportValue: !Sub "StepFunctionExecutionRoleArn-${EnvironmentKey}"
      Definition:
        Comment: "IoT Parking Simulation Flow"
        StartAt: SendDevicesToQueue
        States:

          # Iterate over each device independently
          SendDevicesToQueue:
            Type: Map
            ItemsPath: $.devices  # Each element in 'devices' is processed as a separate iteration
            Iterator:
              StartAt: SendSingleDevice
              States:

                # Enqueue device payload into SQS.
                SendSingleDevice:
                  Type: Task
                  Resource: arn:aws:states:::sqs:sendMessage
                  Parameters:
                    QueueUrl:
                      Fn::ImportValue: !Sub StartProcessingQueueUrl-${EnvironmentKey}
                    MessageBody.$: "$"       # "$" refers to the current device object (e.g. {slotId, status})
                  ResultPath: "$.sqsResult"  # preserve the original input
                  Next: InitRetry       # Continue to next step after message is sent

                # Initialize retry counter per device
                InitRetry:
                  Type: Pass
                  Parameters:
                    slotId.$: "$.slotId"
                    status.$: "$.status"
                    sqsResult.$: "$.sqsResult"
                    retry:
                      attempt: 0
                      maxAttempts: 5
                      waitSeconds: 5
                      # maxAttempts=5 with waitSeconds=5 => ~20s waiting (4 waits), plus Lambda time
                  ResultPath: "$"
                  Next: GetDeviceShadow

                # Call Lambda to read the device shadow state.
                # - Expected output shape: shadow.Payload.isSynced = true|false
                GetDeviceShadow:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  TimeoutSeconds: 3
                  Parameters:
                    FunctionName:
                      Fn::ImportValue: !Sub GetDeviceShadowFunctionArn-${EnvironmentKey}
                    Payload.$: "$"
                  ResultPath: "$.shadow" 
                  Next: IncrementAttempt

                # Increment attempt counter after each shadow read.
                IncrementAttempt:
                  Type: Pass
                  Parameters:
                    slotId.$: "$.slotId"
                    status.$: "$.status"
                    sqsResult.$: "$.sqsResult"
                    shadow.$: "$.shadow"
                    retry:
                      attempt.$: "States.MathAdd($.retry.attempt, 1)"
                      maxAttempts.$: "$.retry.maxAttempts"
                      waitSeconds.$: "$.retry.waitSeconds"
                  ResultPath: "$"
                  Next: CheckSync

                # Validate synchronization - If shadow is synced, end successfully (no SNS notification).
                CheckSync:
                  Type: Choice
                  Choices:
                    - Variable: "$.shadow.Payload.isSynced"
                      BooleanEquals: true
                      Next: EndDevice
                  # Not synced -> decide if we retry or notify (timeout)
                  Default: CheckAttempts

                # Retry gate:
                # - attempt < maxAttempts => wait and retry GetDeviceShadow
                # - else => SNSNotify (timeout)
                CheckAttempts:
                  Type: Choice
                  Choices:
                    - Variable: "$.retry.attempt"
                      NumericLessThanPath: "$.retry.maxAttempts"
                      Next: WaitBeforeRetry
                  Default: SNSNotify

                # Wait before next retry
                WaitBeforeRetry:
                  Type: Wait
                  SecondsPath: "$.retry.waitSeconds"
                  Next: GetDeviceShadow

                # Send notification only after max attempts (timeout)
                SNSNotify:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  TimeoutSeconds: 3
                  Parameters:
                    FunctionName:
                      Fn::ImportValue: !Sub SnsNotifyFunctionArn-${EnvironmentKey}
                    Payload:
                      slotId.$: "$.slotId"
                      status.$: "$.status"
                      deviceId.$: "$.slotId"
                      attempts.$: "$.retry.attempt"
                      maxAttempts.$: "$.retry.maxAttempts"
                      message: "Shadow is not synchronized after max retries"
                  ResultPath: "$.sns"
                  Next: EndDevice

                # End of single device flow
                EndDevice:
                  Type: Succeed
                  Comment: "End of individual device iteration"

            # Continue main flow after all devices are processed
            Next: EndSimulation

          # Step 7: Final state (all devices done)
          EndSimulation:
            Type: Succeed
            Comment: "All device simulations completed"

      TracingConfiguration:
        Enabled: true
      Tags:
        - Key: EnvironmentKey
          Value: !Ref EnvironmentKey

Outputs:
  ParkingStateMachineArn:
    Description: ARN of the IoT Parking Step Function
    Value: !Ref ParkingStateMachine
    Export:
      Name: !Sub ParkingStateMachineArn-${EnvironmentKey}
