AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions for Parking Simulator

Parameters:
  EnvironmentKey:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  IoTEndpointKey:
    Type: String
    Default: a32j14dxvrqa8a-ats.iot.us-east-2.amazonaws.com

Globals:
  Function:
    Runtime: nodejs20.x       # Default runtime for all Lambda functions (Node.js 20)
    Handler: index.handler    # Standard entry point (index.js with "exports.handler")
    MemorySize: 128           # Default memory allocation in MB (lightweight baseline)
    Timeout: 3                # Maximum execution time in seconds (prevents long-running tasks)
    Tracing: Active           # Enables AWS X-Ray tracing for all Lambda functions
    Tags:
      Project: ParkingSimulator 

Resources:
  IoTIngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub iot-ingestion-${EnvironmentKey}
      CodeUri: ../../src/iot-ingestion/
      Role:
        Fn::ImportValue: !Sub IoTIngestionLambdaRoleArn-${EnvironmentKey}

  ## Permiso: permitir que IoT Core invoque la Lambda
  IoTInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IoTIngestionFunction
      Principal: iot.amazonaws.com
      SourceArn:
        Fn::ImportValue: !Sub IoTRuleArn-${EnvironmentKey}

  UpdateDeviceShadowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub updateDeviceShadow-${EnvironmentKey}
      CodeUri: ../../src/updateDeviceShadow/
      Environment:
        Variables:
          IOT_ENDPOINT: !Ref IoTEndpointKey
      Role:
        Fn::ImportValue: !Sub UpdateDeviceShadowLambdaRoleArn-${EnvironmentKey}

  GetShadowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub getDeviceShadow-${EnvironmentKey}
      CodeUri: ../../src/getDeviceShadow/
      Environment:
        Variables:
          IOT_ENDPOINT: !Ref IoTEndpointKey
      Role:
        Fn::ImportValue: !Sub GetDeviceShadowLambdaRoleArn-${EnvironmentKey}

Outputs:
  IoTIngestionLambdaArn:
    Description: ARN of the IoT Ingestion Lambda
    Value: !GetAtt IoTIngestionFunction.Arn
    Export:
      Name: !Sub IoTIngestionLambdaArn-${EnvironmentKey}

  UpdateDeviceShadowFunctionArn:
    Description: ARN of the UpdateDeviceShadow Lambda
    Value: !GetAtt UpdateDeviceShadowFunction.Arn
    Export:
      Name: !Sub UpdateDeviceShadowFunctionArn-${EnvironmentKey}

  GetDeviceShadowFunctionArn:
    Description: ARN of the GetDeviceShadow Lambda
    Value: !GetAtt GetDeviceShadowFunction.Arn
    Export:
      Name: !Sub GetDeviceShadowFunctionArn-${EnvironmentKey}
