AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: IoT Core + Ingestion Lambda stack for Parking Simulator

Parameters:
  EnvironmentKey:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  ## IoT Thing
  ParkingThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: !Sub ParkingThing-${EnvironmentKey}
      AttributePayload:
        Attributes:
          project: iot-parking
          environment: !Ref EnvironmentKey

  ## IoT Policy
  ParkingIoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyName: !Sub ParkingPolicy-${EnvironmentKey}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - iot:Connect
              - iot:Publish
              - iot:Subscribe
              - iot:Receive
            Resource: "*"

  AwsSdkV3Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub aws-sdk-v3-layer-${EnvironmentKey}
      Description: AWS SDK v3 clients for Lambda
      ContentUri: ../../infrastructure/layers/aws-sdk-v3
      CompatibleRuntimes:
        - nodejs20.x

  ## IoT Rule: triggers when a thing shadow delta is generated
  ShadowDeltaIoTRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: !Sub shadowDeltaRule${EnvironmentKey}
      TopicRulePayload:
        AwsIotSqlVersion: "2016-03-23"
        Sql: "SELECT *, topic() AS topic FROM '$aws/things/+/shadow/update/delta'"
        Actions:
          - Lambda:
              FunctionArn:
                Fn::ImportValue: !Sub ShadowDeltaHandlerFunctionArn-${EnvironmentKey}
        RuleDisabled: false
  
  ## Permission for IoT Core to invoke the Lambda
  ShadowDeltaInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::ImportValue: !Sub ShadowDeltaHandlerFunctionArn-${EnvironmentKey}
      Principal: iot.amazonaws.com
      SourceArn: !GetAtt ShadowDeltaIoTRule.Arn

Outputs:
  ThingName:
    Value: !Ref ParkingThing
  PolicyName:
    Value: !Ref ParkingIoTPolicy
